version:"3"
Services:
    nodejs:
        image: nodej
        ports:
            - 
        
    proxy:
        image: apache
        ports:
            - 80:80
    
    db:
        image:postgres
        environment:
            POSTGRES_USER postgres
            POSTGRES_PASSWORD postgres
        